### ISSUE TITLE
Cannot build with XCode 9 & Swift 4

### ISSUE THREAD

**Issue by margusholland** [Pargi/Pargi-iOS#12]
Get the following error:

import Cereal -> Module compiled with Swift 3.1 cannot be imported in Swift 4.0.

**Comment by henrinormak** [comment]
Make sure to update dependencies via Carthage. Fresh build seems to work just fine.

- `git clone --recursive git@github.com:Pargi/Pargi-iOS.git` (`--recursive` for the Data submodule)
- Run `carthage bootstrap`
- Xcode builds

For an already existing checkout, running `carthage update` might also help.

**Comment by margusholland** [comment]
Yes, carthage update fixed it.
